/**https://leetcode.com/problems/find-the-difference/ */
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.


char findTheDifference(char * s, char * t){
    int len1 = strlen(s);
    int len2 = strlen(t);
    int arr[26] = {0};
    for(int i = 0; i < len1; i++){
        arr[s[i] - 'a']++;
    }
    for(int i = 0; i < len2; i++){
        arr[t[i] - 'a']--;
        if(arr[t[i] - 'a'] < 0){
            return t[i];
        }
    }
    return 'a';

}

    