/**https://leetcode.com/problems/find-the-difference/ */
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.


class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] count = new int[26];
        for(int i = 0; i < s.length(); i++){
            count[s.charAt(i) - 'a']++;
        }
        for(int i = 0; i < t.length(); i++){
            count[t.charAt(i) - 'a']--;
            if(count[t.charAt(i) - 'a'] < 0) return t.charAt(i);
        }
        return ' ';
        
    }
}

    