#https://leetcode.com/problems/find-the-difference/
#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """ 
        if len(s)==0:
            return t
        if len(t)==0:
            return s
        if len(s)==1:
            return t[0]
        if len(t)==1:
            return s[0]
        dict={}
        for i in range(0,len(s)):
            if s[i] in dict:
                dict[s[i]]+=1
            else:
                dict[s[i]]=1
        for i in range(0,len(t)):
            if t[i] in dict:
                dict[t[i]]-=1
            else:
                return t[i]
        for key in dict:
            if dict[key]==1:
                return key
        return ""

    